data:
  train_path: "data/splits/train/"
  val_path: "data/splits/val/"
  test_path: "data/splits/test/"
model:
  input_shape: [128, 128, 3]
  output_shape: [128, 128, 1]
training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001